services:
  nsfw-api:
    build: .
    container_name: nsfw_filter_container
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app # 디버그 끝나면 주석처리
      - ./model_cache:/root/.cache/huggingface
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    restart: always